import typing

ItemTypesLiteral = typing.Literal[
    "Airhorn",
    "Big bolt",
    "Bone",
    "Bottles",
    "Brass bell",
    "Candy",
    "Cash register",
    "Chemical jug",
    "Clock",
    "Clown horn",
    "Comedy",
    "Control pad",
    "Cookie mold pan",
    "DIY-Flashbang",
    "Dust pan",
    "Ear",
    "Easter egg",
    "Egg beater",
    "Fancy lamp",
    "Flask",
    "Foot",
    "Garbage lid",
    "Gift Box",
    "Gold bar",
    "Golden cup",
    "Hair brush",
    "Hairdryer",
    "Hand",
    "Heart",
    "Jar of pickles",
    "Knee",
    "Large axle",
    "Laser pointer",
    "Magic 7 ball",
    "Magnifying glass",
    "Metal sheet",
    "Mug",
    "Old phone",
    "Painting",
    "Perfume bottle",
    "Pill bottle",
    "Plastic cup",
    "Plastic fish",
    "Red soda",
    "Remote",
    "Ribcage",
    "Ring",
    "Robot toy",
    "Rubber Ducky",
    "Soccer ball",
    "Steering wheel",
    "Stop sign",
    "Tea kettle",
    "Teeth",
    "Toilet paper",
    "Tongue",
    "Toothpaste",
    "Toy cube",
    "Toy train",
    "Tragedy",
    "V-type engine",
    "Whoopie-Cushion",
    "Yield sign",
    "Zed Dog",
    "",
]
InfestationTypesLiteral = typing.Literal["nutcracker", "lootbug", ""]
MoonTypesLiteral = typing.Literal[
    "experimentation",
    "assurance",
    "vow",
    "offense",
    "march",
    "adamance",
    "rend",
    "dine",
    "titan",
    "artifice",
    "embrion",
    "",
]
WeatherTypesLiteral = typing.Literal[
    "clear", "stormy", "rainy", "flooded", "eclipsed", "foggy"
]
LayoutTypesLiteral = typing.Literal["facility", "mansion", "mineshaft", ""]
RunTypesLiteral = typing.Literal["smhq", "hq"]
